# Generated by Django 4.1.3 on 2022-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='what',
            field=models.BooleanField(default=True),
        ),
    ]
